name: sport_tracker
description: A simple sport tracking app
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  share_plus: ^7.2.1
  test: ^1.24.0

flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^5.0.0